/**
 * CSS Selector Generator
 *
 * Generates a stable CSS selector for a given DOM element.
 * Priority: id > data-testid > data-cy/data-test > data-* > nth-child chain.
 * Validates the selector with querySelector before returning.
 * Returns null for extension elements or detached DOM nodes.
 */

const EXTENSION_IDS = ['feedbacker-extension-root', 'feedbacker-overlay'];

/** Matches UUIDs, hex hashes > 8 chars, and common auto-generated ID patterns. */
const AUTO_GENERATED_ID_RE =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

const HEX_HASH_RE = /^[0-9a-f]{9,}$/i;

/** Patterns like ":r0:", ":r1a:", React 18+ useId output */
const REACT_ID_RE = /^:r[0-9a-z]+:$/;

/** Numeric-only IDs are usually auto-generated */
const NUMERIC_ID_RE = /^\d+$/;

function isAutoGeneratedId(id: string): boolean {
  return (
    AUTO_GENERATED_ID_RE.test(id) ||
    HEX_HASH_RE.test(id) ||
    REACT_ID_RE.test(id) ||
    NUMERIC_ID_RE.test(id)
  );
}

function isExtensionElement(el: Element): boolean {
  let node: Node | null = el;
  while (node) {
    if (node instanceof HTMLElement) {
      if (EXTENSION_IDS.includes(node.id)) {
        return true;
      }
    }
    node = node.parentNode;
  }
  return false;
}

function isAttachedToDocument(el: Element): boolean {
  return el.isConnected;
}

function escapeCSS(value: string): string {
  if (typeof CSS !== 'undefined' && typeof CSS.escape === 'function') {
    return CSS.escape(value);
  }
  // Fallback for environments without CSS.escape (e.g., jsdom in tests).
  // Escapes characters that are not valid in CSS identifiers.
  return value.replace(/([\0-\x1f\x7f]|^-?\d|[^\w-])/g, (ch) => {
    if (ch === '\0') return '\uFFFD';
    const code = ch.charCodeAt(0);
    return `\\${code.toString(16)} `;
  });
}

function getNthChildIndex(el: Element): number {
  let index = 1;
  let sibling = el.previousElementSibling;
  while (sibling) {
    index++;
    sibling = sibling.previousElementSibling;
  }
  return index;
}

function trySelector(selector: string, target: Element): boolean {
  try {
    return document.querySelector(selector) === target;
  } catch {
    return false;
  }
}

/** Try to build a selector from the element's own id attribute. */
function tryIdSelector(el: HTMLElement): string | null {
  const id = el.id;
  if (!id || isAutoGeneratedId(id) || EXTENSION_IDS.includes(id)) {
    return null;
  }
  const selector = `#${escapeCSS(id)}`;
  return trySelector(selector, el) ? selector : null;
}

/** Try data-testid attribute. */
function tryDataTestId(el: HTMLElement): string | null {
  const value = el.getAttribute('data-testid');
  if (!value) return null;
  const selector = `[data-testid="${escapeCSS(value)}"]`;
  return trySelector(selector, el) ? selector : null;
}

/** Try data-cy or data-test attributes. */
function tryDataCyOrTest(el: HTMLElement): string | null {
  for (const attr of ['data-cy', 'data-test']) {
    const value = el.getAttribute(attr);
    if (!value) continue;
    const selector = `[${attr}="${escapeCSS(value)}"]`;
    if (trySelector(selector, el)) return selector;
  }
  return null;
}

/** Try other data-* attributes with stable-looking values. */
function tryCustomDataAttrs(el: HTMLElement): string | null {
  const attrs = Array.from(el.attributes);
  for (const attr of attrs) {
    if (
      attr.name.startsWith('data-') &&
      !['data-testid', 'data-cy', 'data-test'].includes(attr.name) &&
      attr.value &&
      !isAutoGeneratedId(attr.value)
    ) {
      const selector = `[${attr.name}="${escapeCSS(attr.value)}"]`;
      if (trySelector(selector, el)) return selector;
    }
  }
  return null;
}

/** Build an nth-child path segment for a single element. */
function buildSegment(el: Element): string {
  const tag = el.tagName.toLowerCase();
  const index = getNthChildIndex(el);
  return `${tag}:nth-child(${index})`;
}

/**
 * Build an nth-child chain from the nearest ancestor with an ID or
 * unique data attribute, or from body as a last resort.
 */
function buildNthChildChain(el: HTMLElement): string | null {
  const segments: string[] = [];
  let current: Element | null = el;

  while (current && current !== document.documentElement) {
    if (current === document.body) {
      segments.unshift('body');
      break;
    }

    // Check if this ancestor has a usable id
    if (current !== el && current instanceof HTMLElement && current.id) {
      if (!isAutoGeneratedId(current.id) && !EXTENSION_IDS.includes(current.id)) {
        segments.unshift(`#${escapeCSS(current.id)}`);
        break;
      }
    }

    segments.unshift(buildSegment(current));
    current = current.parentElement;
  }

  // If we ran out of parents without hitting body, start from body
  if (segments.length > 0 && segments[0] !== 'body' && !segments[0].startsWith('#')) {
    segments.unshift('body');
  }

  const selector = segments.join(' > ');
  return trySelector(selector, el) ? selector : null;
}

/**
 * Generates a CSS selector for the given element.
 *
 * Returns null if:
 * - The element is part of the feedbacker extension
 * - The element is detached from the DOM
 * - No valid selector could be generated
 */
export function generateCssSelector(element: HTMLElement): string | null {
  if (!isAttachedToDocument(element)) return null;
  if (isExtensionElement(element)) return null;

  // Priority 1: id
  const idSel = tryIdSelector(element);
  if (idSel) return idSel;

  // Priority 2: data-testid
  const testIdSel = tryDataTestId(element);
  if (testIdSel) return testIdSel;

  // Priority 3: data-cy / data-test
  const cyTestSel = tryDataCyOrTest(element);
  if (cyTestSel) return cyTestSel;

  // Priority 4: other data-* attributes
  const dataSel = tryCustomDataAttrs(element);
  if (dataSel) return dataSel;

  // Priority 5-6: nth-child chain
  const nthSel = buildNthChildChain(element);
  if (nthSel) return nthSel;

  return null;
}
