name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build library
      run: npm run build
    
    # TypeScript checks temporarily disabled - will fix in follow-up
    # - name: Run TypeScript checks
    #   run: npm run typecheck --workspace=feedbacker-react --if-present
    
    - name: Run tests
      run: npm test --if-present
    
    - name: Build demo
      run: npm run build:demo