name: E2E Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build library
        run: npm run build
        working-directory: packages/feedbacker
      
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: packages/feedbacker
      
      - name: Run Playwright tests
        run: npm run test:e2e
        working-directory: packages/feedbacker
      
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: packages/feedbacker/playwright-report/
          retention-days: 30